const english = ['ant', 'apple', 'autumn leaves', 'banana', 'bear', 'bed', 'bicycle', 'bird', 'book', 'boots', 'bread', 'bullet train', 'bus', 'cabbage', 'camera', 'car', 'carrot', 'cat', 'chair', 'cheeks', 'cherries', 'chopstick', 'circle', 'clock', 'cloud', 'cube', 'cucumber', 'cup', 'delicious', 'door', 'dragonfly', 'drum', 'earth', 'egg', 'eggplant', 'eight', 'electrical outlets', 'elephant', 'excavator', 'eye', 'fire', 'fish', 'fishing', 'five', 'flower', 'fork', 'four', 'futon', 'giraffe', 'glasses', 'good morning', 'good night', 'good-bye', 'grape', 'green bell pepper', 'guitar', 'hair dryer', 'hair', 'hand', 'hanger', 'hat',
    'head', 'hello', 'house', 'kettle', 'ladle', 'ladybug', 'leaf', 'leg', 'lettuce', 'light bulb', 'light', 'melon', 'microphone', 'milk', 'money', 'moon', 'mountain', 'mouth', 'nail', 'nine', 'nose', 'one', 'onion', 'painting', 'peach', 'pear', 'pencil', 'penguin', 'phone', 'picture book', 'pillow', 'plane', 'potato', 'radish', 'rain', 'rainbow', 'refrigerater', 'rice', 'river', 'rocket', 'saucepan', 'scissors', 'seven', 'shaved ice', 'ship', 'six', 'slide', 'slippers', 'snake', 'snow man', 'soap bubbles', 'soap', 'soft ice', 'square', 'star', 'strawberry', 'sun', 'swing', 'table', 'taxi', 'ten', 'three', 'tire', 'toilet', 'tomato', 'tongue', 'toothbrush', 'tortoise', 'toy', 'train', 'tree', 'triangle', 'two', 'umbrella', 'waist', 'watermelon', 'window'];
const hiragana = ["あり", "りんご", "もみじ", "バナナ", "くま", "ベッド", "じてんしゃ", "とり", "ほん", "ブーツ", "パン", "しんかんせん", "バス", "キャベツ", "カメラ", "くるま", "にんじん", "ねこ", "いす", "ほっぺ", "さくらんぼ", "はし", "まる", "とけい", "くも", "りっぽうたい", "きゅうり", "カップ", "おいしい", "ドア", "とんぼ", "たいこ", "ちきゅう", "たまご", "なす", "はち", "コンセント", "ぞう",
    "ショベルカー", "め", "ひ", "さかな", "つり", "ご", "はな", "フォーク", "よん", "ふとん", "きりん", "めがね", "おはよう", "おやすみ", "さようなら", "ぶどう", "ピーマン", "ギター", "ドライヤー", "かみ", "て", "ハンガー", "ぼうし",
    "あたま", "こんにちは", "いえ", "やかん", "おたま", "てんとうむし", "はっぱ", "あし", "レタス", "でんきゅう", "ライト", "メロン", "マイク", "ぎゅうにゅう", "おかね", "つき", "やま", "くち", "つめ", "きゅう", "はな", "いち", "たまねぎ", "え", "もも", "なし", "えんぴつ", "ペンギン", "でんわ", "えほん", "まくら", "ひこうき", "じゃがいも", "だいこん", "あめ", "にじ", "れいぞうこ", "ごはん", "かわ", "ロケット", "なべ", "はさみ", "なな", "かきごおり", "ふね", "ろく", "すべりだい", "スリッパ", "へび", "ゆきだるま", "しゃぼんだま", "せっけん", "ソフトクリーム", "しかく", "ほし", "いちご", "たいよう", "ぶらんこ", "テーブル", "タクシー", "じゅう", "さん", "タイヤ", "といれ", "とまと", "した", "はぶらし", "かめ", "おもちゃ", "でんしゃ", "き", "さんかく", "に", "かさ", "こし", "すいか", "まど"
];
const kanji = ["蟻", "林檎", "紅葉", "バナナ", "熊", "ベッド", "自転車", "鳥", "本", "ブーツ", "パン", "新幹線", "バス", "キャベツ", "カメラ", "車", "人参", "猫", "椅子", "頬", "桜桃", "箸", "丸", "時計", "雲", "立方体", "胡瓜", "カップ", "美味しい", "ドア", "蜻蛉", "太鼓", "地球", "卵", "茄子", "八", "コンセント", "象",
    "ショベルカー", "目", "火", "魚", "釣り", "五", "花", "フォーク", "四", "布団", "麒麟", "眼鏡", "おはよう", "お休", "さようなら", "葡萄", "ピーマン", "ギター", "ドライヤー", "髪", "手", "ハンガー", "帽子",
    "頭", "こんにちは", "家", "薬缶", "お玉", "天道虫", "葉", "足", "レタス", "電球", "ライト", "メロン", "マイク", "牛乳", "お金", "月", "山", "口", "爪", "九", "鼻", "一", "玉葱", "絵", "桃", "梨", "鉛筆", "ペンギン", "電話", "絵本", "枕", "飛行機", "ジャガイモ", "大根", "雨", "虹", "冷蔵庫", "ご飯", "川", "ロケット", "鍋", "鋏", "七", "かき氷", "船", "六", "滑り台", "スリッパ", "蛇", "雪だるま", "シャボン玉", "石鹸", "ソフトクリーム", "四角", "星", "苺", "太陽", "ブランコ", "テーブル", "タクシー", "十", "三", "タイヤ", "トイレ", "トマト", "舌", "歯ブラシ", "亀", "玩具", "電車", "木", "三角", "二", "傘", "腰", "西瓜", "窓"
];
const espaniol = [
    "hormiga", "manzana", "hojas de otoño", "plátano", "oso", "cama", "bicicleta", "pájaro", "libro", "botas", "pan", "tren bala", "autobús", "repollo", "cámara", "coche", "zanahoria", "gato", "silla", "mejillas", "cerezas", "palillos", "círculo", "reloj", "nube", "cubo", "pepino", "taza", "delicioso", "puerta", "libélula", "tambor", "tierra", "huevo", "berenjena", "ocho", "enchufes", "elefante",
    "excavadora", "ojo", "fuego", "pez", "pesca", "cinco", "flor", "tenedor", "cuatro", "futón", "jirafa", "gafas", "buenos días", "buenas noches", "adiós", "uva", "pimiento verde", "guitarra", "secador de pelo", "pelo", "mano", "percha", "sombrero",
    "cabeza", "hola", "casa", "tetera", "cucharón", "mariquita", "hoja", "pierna", "lechuga", "bombilla", "luz", "melón", "micrófono", "leche", "dinero", "luna", "montaña", "boca", "uña", "nueve", "nariz", "uno", "cebolla", "pintura", "melocotón", "pera", "lápiz", "pingüino", "teléfono", "libro de imágenes", "almohada", "avión", "patata", "rábano", "lluvia", "arcoíris", "refrigerador", "arroz", "río", "cohete", "cacerola", "tijeras", "siete", "hielo raspado", "barco", "seis", "tobogán", "zapatillas", "serpiente", "muñeco de nieve", "burbujas de jabón", "jabón", "helado", "cuadrado", "estrella", "fresa", "sol", "columpio", "mesa", "taxi", "diez", "tres", "neumático", "inodoro", "tomate", "lengua", "cepillo de dientes", "tortuga", "juguete", "tren", "árbol", "triángulo", "dos", "paraguas", "cintura", "sandía", "ventana"
];
const portuguesa = [
    "formiga", "maçã", "folhas de outono", "banana", "urso", "cama", "bicicleta", "pássaro", "livro", "botas", "pão", "trem-bala", "ônibus", "repolho", "câmera", "carro", "cenoura", "gato", "cadeira", "bochechas", "cerejas", "hashi", "círculo", "relógio", "nuvem", "cubo", "pepino", "copo", "delicioso", "porta", "libélula", "tambor", "terra", "ovo", "berinjela", "oito", "tomadas elétricas", "elefante",
    "escavadeira", "olho", "fogo", "peixe", "pescaria", "cinco", "flor", "garfo", "quatro", "futon", "girafa", "óculos", "bom dia", "boa noite", "adeus", "uva", "pimentão verde", "guitarra", "secador de cabelo", "cabelo", "mão", "cabide", "chapéu",
    "cabeça", "olá", "casa", "chaleira", "concha", "joaninha", "folha", "perna", "alface", "lâmpada", "luz", "melão", "microfone", "leite", "dinheiro", "lua", "montanha", "boca", "unha", "nove", "nariz", "um", "cebola", "pintura", "pêssego", "pera", "lápis", "pinguim", "telefone", "livro ilustrado", "travesseiro", "avião", "batata", "rabanete", "chuva", "arco-íris", "geladeira", "arroz", "rio", "foguete", "panela", "tesoura", "sete", "gelo raspado", "navio", "seis", "escorregador", "chinelos", "cobra", "boneco de neve", "bolhas de sabão", "sabão", "sorvete", "quadrado", "estrela", "morango", "sol", "balanço", "mesa", "táxi", "dez", "três", "pneu", "banheiro", "tomate", "língua", "escova de dentes", "tartaruga", "brinquedo", "trem", "árvore", "triângulo", "dois", "guarda-chuva", "cintura", "melancia", "janela"
];

const russia = [
    "муравей", "яблоко", "осенние листья", "банан", "медведь", "кровать", "велосипед", "птица", "книга", "ботинки", "хлеб", "скоростной поезд", "автобус", "капуста", "фотоаппарат", "машина", "морковь", "кошка", "стул", "щёки", "вишня", "палочки для еды", "круг", "часы", "облако", "куб", "огурец", "чашка", "вкусно", "дверь", "стрекоза", "барабан", "земля", "яйцо", "баклажан", "восемь", "электрические розетки", "слон",
    "экскаватор", "глаз", "огонь", "рыба", "рыбалка", "пять", "цветок", "вилка", "четыре", "футон", "жираф", "очки", "доброе утро", "спокойной ночи", "до свидания", "виноград", "зелёный болгарский перец", "гитара", "фен", "волосы", "рука", "вешалка", "шляпа",
    "голова", "здравствуйте", "дом", "чайник", "половник", "божья коровка", "лист", "нога", "салат", "лампочка", "свет", "дыня", "микрофон", "молоко", "деньги", "луна", "гора", "рот", "гвоздь", "девять", "нос", "один", "лук", "картина", "персик", "груша", "карандаш", "пингвин", "телефон", "книжка с картинками", "подушка", "самолёт", "картофель", "редис", "дождь", "радуга", "холодильник", "рис", "река", "ракета", "кастрюля", "ножницы", "семь", "бритый лёд", "корабль", "шесть", "горка", "тапочки", "змея", "снеговик", "мыльные пузыри", "мыло", "мягкое мороженое", "квадрат", "звезда", "клубника", "солнце", "качели", "стол", "такси", "десять", "три", "шина", "туалет", "помидор", "язык", "зубная щётка", "черепаха", "игрушка", "поезд", "дерево", "треугольник", "два", "зонт", "талия", "арбуз", "окно"
];
const italy = [
    "formica", "mela", "foglie autunnali", "banana", "orso", "letto", "bicicletta", "uccello", "libro", "stivali", "pane", "treno proiettile", "autobus", "cavolo", "macchina fotografica", "macchina", "carota", "gatto", "sedia", "guance", "ciliegie", "bacchette", "cerchio", "orologio", "nuvola", "cubo", "cetriolo", "tazza", "delizioso", "porta", "libellula", "tamburo", "terra", "uovo", "melanzana", "otto", "prese elettriche", "elefante",
    "escavatore", "occhio", "fuoco", "pesce", "pesca", "cinque", "fiore", "forchetta", "quattro", "futon", "giraffa", "occhiali", "buongiorno", "buona notte", "arrivederci", "uva", "peperone verde", "chitarra", "asciugacapelli", "capelli", "mano", "appendiabiti", "cappello",
    "testa", "ciao", "casa", "bollitore", "mestolo", "coccinella", "foglia", "gamba", "lattuga", "lampadina", "luce", "melone", "microfono", "latte", "soldi", "luna", "montagna", "bocca", "unghia", "nove", "naso", "uno", "cipolla", "dipinto", "pesca", "pera", "matita", "pinguino", "telefono", "libro illustrato", "cuscino", "aereo", "patata", "ravanello", "pioggia", "arcobaleno", "frigorifero", "riso", "fiume", "razzo", "pentola", "forbici", "sette", "granita", "nave", "sei", "scivolo", "pantofole", "serpente", "pupazzo di neve", "bolle di sapone", "sapone", "gelato", "quadrato", "stella", "fragola", "sole", "altalena", "tavolo", "taxi", "dieci", "tre", "pneumatico", "toilette", "pomodoro", "lingua", "spazzolino da denti", "tartaruga", "giocattolo", "treno", "albero", "triangolo", "due", "ombrello", "vita", "cocomero", "finestra"
];

const french = [
    "fourmi", "pomme", "feuilles d'automne", "banane", "ours", "lit", "bicyclette", "oiseau", "livre", "bottes", "pain", "train à grande vitesse", "bus", "chou", "appareil photo", "voiture", "carotte", "chat", "chaise", "joues", "cerises", "baguettes", "cercle", "horloge", "nuage", "cube", "concombre", "tasse", "délicieux", "porte", "libellule", "tambour", "terre", "œuf", "aubergine", "huit", "prises électriques", "éléphant",
    "excavatrice", "œil", "feu", "poisson", "pêche", "cinq", "fleur", "fourchette", "quatre", "futon", "girafe", "lunettes", "bonjour", "bonne nuit", "au revoir", "raisin", "poivron vert", "guitare", "sèche-cheveux", "cheveux", "main", "cintre", "chapeau",
    "tête", "bonjour", "maison", "bouilloire", "louche", "coccinelle", "feuille", "jambe", "laitue", "ampoule", "lumière", "melon", "microphone", "lait", "argent", "lune", "montagne", "bouche", "ongle", "neuf", "nez", "un", "oignon", "peinture", "pêche", "poire", "crayon", "pingouin", "téléphone", "livre d'images", "oreiller", "avion", "pomme de terre", "radis", "pluie", "arc-en-ciel", "réfrigérateur", "riz", "rivière", "fusée", "casserole", "ciseaux", "sept", "glace pilée", "navire", "six", "toboggan", "pantoufles", "serpent", "bonhomme de neige", "bulles de savon", "savon", "glace molle", "carré", "étoile", "fraise", "soleil", "balançoire", "table", "taxi", "dix", "trois", "pneu", "toilettes", "tomate", "langue", "brosse à dents", "tortue", "jouet", "train", "arbre", "triangle", "deux", "parapluie", "taille", "pastèque", "fenêtre"
];
const chinese = [
    "蚂蚁", "苹果", "秋叶", "香蕉", "熊", "床", "自行车", "鸟", "书", "靴子", "面包", "新干线", "公共汽车", "卷心菜", "照相机", "汽车", "胡萝卜", "猫", "椅子", "脸颊", "樱桃", "筷子", "圆圈", "时钟", "云", "立方体", "黄瓜", "杯子", "美味", "门", "蜻蜓", "鼓", "地球", "鸡蛋", "茄子", "八", "电源插座", "大象",
    "挖掘机", "眼睛", "火", "鱼", "钓鱼", "五", "花", "叉子", "四", "被褥", "长颈鹿", "眼镜", "早上好", "晚安", "再见", "葡萄", "青椒", "吉他", "吹风机", "头发", "手", "衣架", "帽子",
    "头", "你好", "房子", "水壶", "勺子", "瓢虫", "叶子", "腿", "生菜", "灯泡", "灯", "甜瓜", "麦克风", "牛奶", "钱", "月亮", "山", "嘴巴", "指甲", "九", "鼻子", "一", "洋葱", "绘画", "桃子", "梨", "铅笔", "企鹅", "电话", "图画书", "枕头", "飞机", "土豆", "萝卜", "雨", "彩虹", "冰箱", "米饭", "河", "火箭", "平底锅", "剪刀", "七", "刨冰", "船", "六", "滑梯", "拖鞋", "蛇", "雪人", "肥皂泡", "肥皂", "软冰淇淋", "正方形", "星星", "草莓", "太阳", "秋千", "桌子", "出租车", "十", "三", "轮胎", "厕所", "西红柿", "舌头", "牙刷", "乌龟", "玩具", "火车", "树", "三角形", "二", "雨伞", "腰", "西瓜", "窗户"
];
const korean = [
    "개미", "사과", "가을 단풍", "바나나", "곰", "침대", "자전거", "새", "책", "부츠", "빵", "고속 열차", "버스", "양배추", "카메라", "자동차", "당근", "고양이", "의자", "볼", "체리", "젓가락", "원", "시계", "구름", "정육면체", "오이", "컵", "맛있다", "문", "잠자리", "북", "지구", "달걀", "가지", "여덟", "전기 콘센트", "코끼리",
    "굴착기", "눈", "불", "물고기", "낚시", "다섯", "꽃", "포크", "넷", "요", "기린", "안경", "안녕하세요", "안녕히 주무세요", "안녕", "포도", "피망", "기타", "헤어 드라이어", "머리카락", "손", "옷걸이", "모자",
    "머리", "안녕하세요", "집", "주전자", "국자", "무당벌레", "나뭇잎", "다리", "상추", "전구", "빛", "멜론", "마이크", "우유", "돈", "달", "산", "입", "손톱", "아홉", "코", "하나", "양파", "그림", "복숭아", "배", "연필", "펭귄", "전화", "그림책", "베개", "비행기", "감자", "무", "비", "무지개", "냉장고", "밥", "강", "로켓", "냄비", "가위", "일곱", "빙수", "배", "여섯", "미끄럼틀", "슬리퍼", "뱀", "눈사람", "비눗방울", "비누", "소프트 아이스크림", "정사각형", "별", "딸기", "태양", "그네", "테이블", "택시", "열", "셋", "타이어", "화장실", "토마토", "혀", "칫솔", "거북이", "장난감", "기차", "나무", "삼각형", "둘", "우산", "허리", "수박", "창문"
];